sets.exported={
    main="Naegling",
    sub="Sakpata's Sword",
    ammo="Ombre Tathlum +1",
    head="Malignance Chapeau",
    body="Malignance Tabard",
    hands="Malignance Gloves",
    legs="Malignance Tights",
    feet="Nyame Sollerets",
    neck={ name="Mirage Stole +2", augments={'Path: A',}},
    waist="Luminary Sash",
    left_ear="Hermetic Earring",
    right_ear="Gwati Earring",
    left_ring="Stikini Ring",
    right_ring="Stikini Ring",
    back={ name="Cornflower Cape", augments={'MP+21','Accuracy+4','Blue Magic skill +8',}},
}