sets.exported={
    main={ name="Masamune", augments={'Path: A',}},
    sub="Utu Grip",
    ammo="Knobkierrie",
    head="Mpaca's Cap",
    body={ name="Sakonji Domaru +3", augments={'Enhances "Overwhelm" effect',}},
    hands="Nyame Gauntlets",
    legs="Wakido Haidate +3",
    feet="Nyame Sollerets",
    neck={ name="Sam. Nodowa +2", augments={'Path: A',}},
    waist="Orpheus's Sash",
    left_ear="Thrud Earring",
    right_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    left_ring="Defending Ring",
    right_ring="Niqmaddu Ring",
    back={ name="Smertrios's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
}