sets.exported={
    main="Perun",
    sub="Nusku Shield",
    range="Annihilator",
    ammo="Eradicating Bullet",
    head="Malignance Chapeau",
    body="Malignance Tabard",
    hands="Malignance Gloves",
    legs="Malignance Tights",
    feet="Malignance Boots",
    neck={ name="Scout's Gorget +2", augments={'Path: A',}},
    waist="Eschan Stone",
    left_ear="Telos Earring",
    right_ear="Dedition Earring",
    left_ring="Ilabrat Ring",
    right_ring="Chirich Ring +1",
    back={ name="Belenus's Cape", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
}