sets.exported={
    main="Naegling",
    sub="Blurred Knife +1",
    range={ name="Sparrowhawk +2", augments={'TP Bonus +1000',}},
    ammo="Hauksbok Arrow",
    head="Nyame Helm",
    body="Amini Caban +2",
    hands="Nyame Gauntlets",
    legs="Nyame Flanchard",
    feet="Amini Bottillons +2",
    neck={ name="Bathy Choker +1", augments={'Path: A',}},
    waist="Svelt. Gouriz +1",
    left_ear="Infused Earring",
    right_ear="Eabani Earring",
    left_ring="Defending Ring",
    right_ring="Warp Ring",
    back="Moonlight Cape",
}