sets.exported={
    main="Sequence",
    ammo="Staunch Tathlum",
    head="Malignance Chapeau",
    body="Malignance Tabard",
    hands="Malignance Gloves",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet="Hippo. Socks +1",
    neck={ name="Loricate Torque +1", augments={'Path: A',}},
    waist="Eschan Stone",
    left_ear="Genmei Earring",
    right_ear="Loquac. Earring",
    left_ring="Gelatinous Ring",
    right_ring="Defending Ring",
    back="Solemnity Cape",
}