sets.exported={
    main="Naegling",
    ammo="Coiste Bodhar",
    head={ name="Herculean Helm", augments={'Attack+7','Weapon skill damage +3%','STR+14','Accuracy+11',}},
    body="Malignance Tabard",
    hands="Meg. Gloves +2",
    legs="Malignance Tights",
    feet="Malignance Boots",
    neck="Caro Necklace",
    waist={ name="Sailfi Belt +1", augments={'Path: A',}},
    left_ear="Ishvara Earring",
    right_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
    right_ring="Beithir Ring",
    back="Moonlight Cape",
}