sets.exported={
    main={ name="Crocea Mors", augments={'Path: C',}},
    sub="Daybreak",
    ammo="Amar Cluster",
    head="Leth. Chappel +2",
    body="Lethargy Sayon +2",
    hands="Leth. Gantherots +1",
    legs="Leth. Fuseau +2",
    feet="Leth. Houseaux +3",
    neck={ name="Bathy Choker +1", augments={'Path: A',}},
    waist="Svelt. Gouriz +1",
    left_ear="Eabani Earring",
    right_ear="Infused Earring",
    left_ring="Defending Ring",
    right_ring="Warp Ring",
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','MND+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
}