sets.exported={
    main="Sakpata's Sword",
    sub={ name="Priwen", augments={'HP+50','Mag. Evasion+50','Damage Taken -3%',}},
    ammo="Staunch Tathlum",
    head={ name="Yorium Barbuta", augments={'Spell interruption rate down -9%','Phalanx +3',}},
    body={ name="Yorium Cuirass", augments={'Spell interruption rate down -10%','Phalanx +3',}},
    hands={ name="Souv. Handsch. +1", augments={'HP+105','Enmity+9','Potency of "Cure" effect received +15%',}},
    legs={ name="Yorium Cuisses", augments={'Spell interruption rate down -10%','Phalanx +3',}},
    feet={ name="Souveran Schuhs +1", augments={'HP+105','Enmity+9','Potency of "Cure" effect received +15%',}},
    neck="Moonlight Necklace",
    waist="Olympus Sash",
    left_ear="Thureous Earring",
    right_ear="Loquac. Earring",
    left_ring="Stikini Ring",
    right_ring="Stikini Ring",
    back={ name="Weard Mantle", augments={'VIT+2','DEX+2','Enmity+2','Phalanx +3',}},
}