sets.exported={
    main="Bunzi's Rod",
    sub="Naegling",
    ammo="Mavi Tathlum",
    body={ name="Cohort Cloak +1", augments={'Path: A',}},
    hands={ name="Amalric Gages +1", augments={'INT+12','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    legs="Nyame Flanchard",
    feet={ name="Amalric Nails +1", augments={'Mag. Acc.+20','"Mag.Atk.Bns."+20','"Conserve MP"+7',}},
    neck={ name="Mirage Stole +2", augments={'Path: A',}},
    waist="Orpheus's Sash",
    left_ear="Hecate's Earring",
    right_ear="Friomisi Earring",
    left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
    right_ring="Shiva Ring +1",
    back="Solemnity Cape",
}