sets.exported={
    main={ name="Rostam", augments={'Path: C',}},
    range={ name="Compensator", augments={'DMG:+15','AGI+15','Rng.Acc.+15',}},
    ammo="Chrono Bullet",
    head="Chass. Tricorne +1",
    body="Laksa. Frac +3",
    hands={ name="Lanun Gants +3", augments={'Enhances "Fold" effect',}},
    legs={ name="Adhemar Kecks +1", augments={'AGI+12','"Rapid Shot"+13','Enmity-6',}},
    feet="Meg. Jam. +2",
    neck={ name="Comm. Charm +2", augments={'Path: A',}},
    waist="Yemaya Belt",
    left_ear="Pixie Earring",
    right_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    left_ring="Defending Ring",
    right_ring="Dim. Ring (Holla)",
    back={ name="Camulus's Mantle", augments={'"Snapshot"+10',}},
}