sets.exported={
    main={ name="Rostam", augments={'Path: C',}},
    sub="Blurred Knife +1",
    range={ name="Compensator", augments={'DMG:+15','AGI+15','Rng.Acc.+15',}},
    ammo="Chrono Bullet",
    head="Mummu Bonnet +1",
    body="Mummu Jacket +1",
    hands="Malignance Gloves",
    legs="Meg. Chausses +2",
    feet="Malignance Boots",
    neck="Loricate Torque",
    waist="Sarissapho. Belt",
    left_ear="Pixie Earring",
    right_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    left_ring="Defending Ring",
    right_ring="Dim. Ring (Holla)",
    back={ name="Camulus's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dual Wield"+10','Phys. dmg. taken-10%',}},
}